var data = [{
		"url": "images/pic/furongsi.png",
		"w": "426",
		"h": "187",
		"x": "3060",
		"y": "1850",
		"txt": "黄江芙蓉寺",
		"aLink": "",
		"sprite": false,
		"step": 0,
		"scenepPoit": "huangjiangfurongshi",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/guanyinshan.png",
		"w": "487",
		"h": "296",
		"x": "3242",
		"y": "1449",
		"txt": "东莞观音山国家森林公园",
		"aLink": "http://www.guanyinshan.com",
		"sprite": false,
		"step": 0,
		"scenepPoit": "guanyinshan",
		"info": "全国首家民营国家级森林公园，园区总面积18平方公里，森林覆盖率达99%以上，是集生态观光、娱乐健身和宗教文化为一体的国家AAAA级旅游景区，被誉为“南天圣地、百粤秘境”。荣获“中国十佳休闲景区”、“中国最佳旅游目的地”、“广东大学生最喜爱的景区”等称号；联合国环境规划署认定的“中国最具发展潜力的企业”和“国际生态安全旅游示范基地”。观音山历史悠久，环境清幽，风景秀丽，空气清新，珍禽异兽时有出没，奇花异草漫山遍野。公园内景点林立，一步一景，主要景点有：慈云阁、国际会展中心、蔡子培将军像、八仙过海、观音广场、财神殿、大悲殿、感恩湖、三十六级瀑布等。园区内的观音山古树博物馆是国内首家古树博物馆，收藏了近年来出土的有研究价值和观赏价值的古树近百棵，先后被授予东莞市首批“科普教育基地”和“广东省青少年科普教育基地”称号。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/baota.png",
		"w": "396",
		"h": "283",
		"x": "1123",
		"y": "485",
		"txt": "金鳌塔",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "jinaota",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/dongguanzhiwuyuan.png",
		"w": "334",
		"h": "163",
		"x": "1473",
		"y": "1286",
		"txt": "东莞市植物园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "zhiwuyuan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/dongkengnongyeyuan.png",
		"w": "373",
		"h": "168",
		"x": "2764",
		"y": "1131",
		"txt": "东坑湿地公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "dongkengshidi",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/gaobuzhen.png",
		"w": "141",
		"h": "171",
		"x": "1319",
		"y": "338",
		"txt": "唯美陶瓷博物馆 ",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "weimeitaoci",
		"info": "由企业兴建的产业资源类博物馆，耗资3000万元、占地2万多平方米，地处广东省唯美陶瓷有限公司总部，内有展品、藏品近8万余件，共分为唯美陶瓷馆、唯美历史陈列室、唯美壁饰展、唯美装饰展、唯美创作礼品作品展、中国建筑陶瓷史展厅、陈复澄唯美艺术馆及陶艺馆等8个展厅，是一个集陶瓷、书画艺术品展示与企业建筑陶瓷发展历史、中国陶瓷发展历史于一体的陶瓷博物馆。</br>展馆一层富有现代气息，主要展示马可波罗和L&D两大主导品牌产品。整个展厅布局独具匠心，整体与局部处理恰到好处，幽雅的环境让置身其中的参观者心情放松，感叹连连。位于博物馆二三楼的唯美壁饰展、唯美装饰展、唯美创作礼品作品展、陈复澄唯美艺术馆等4个展馆、唯美历史陈列室一系列展示让参观者强烈感受到唯美企业特殊的背景和发展历程。中国建筑陶瓷史展厅则让人更加了解中国博大精深的建筑陶瓷文化。最受欢迎的应属互动型展厅陶艺馆，让观者在参与陶艺制作体验中回味无穷。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/yapianzhanzheng.png",
		"w": "239",
		"h": "328",
		"x": "908",
		"y": "2123",
		"txt": "鸦片战争博物馆",
		"aLink": "http://www.ypzz.cn",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yapianzhanzhengbowuguan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/nuohuajiaju.png",
		"w": "158",
		"h": "214",
		"x": "1034",
		"y": "987",
		"txt": "诺华中式家居博物馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/zhangmutouzhen.png",
		"w": "201",
		"h": "203",
		"x": "3721",
		"y": "1446",
		"txt": "冠和博物馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "guanhebowuguan",
		"info": "以收藏、展示、研究历代文物为主的综合性私人博物馆，广东省最大的民营博物馆，也是全国第一家以古典家具展览为主的博物馆，是国家AA级旅游景区。</br>博物馆藏品颇丰，分为紫檀区、大长条案横匾区、民初区、兵器乐器区、大柜大床区等10个展区。古典家具展主要是以明、清两朝代为主，年代跨度为543年（公元1368—1911年），这个时期是传统家具的黄金时代，明代家具高大威昂，线条优美，花纹简朴，很有气派；清代家具精雕细刻、图案繁多，追求宫廷式的富丽堂皇。</br>博物馆除了古典家具藏品外，收藏陈列的藏品还有兵器、陶瓷、书画、木雕、根雕、古乐器、民间工艺绣品、古代农村生活工具、文革时期纪念品、西方古典用具等十几个类别。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/senhui.png",
		"w": "192",
		"h": "121",
		"x": "1391",
		"y": "606",
		"txt": "森晖自然博物馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "shenhuiziranbowuguan",
		"info": "占地面积12000多平方米，博物馆展馆建筑面积6000多平方米，古玩城建筑面积约8000平方米。</br>博物馆主要集古生物化石、根雕、奇石、名人字画、木雕等领域的收藏、展览、研究和科普等于一体，是一家规模较大、藏品较多、设施完善、功能齐备的自然科学博物馆；古玩城内设展览交流培训中心，精优商铺，主要经营以古典家具、奇石、根雕、翡翠、玉器、书画、瓷器、陶器、沉香、杂项等商品，是东莞较集中化、规模化、专业化，具备商务交流信息传播，培训鉴定，休闲淘宝，艺术创造为一体的古玩城。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/mingjiaju.png",
		"w": "391",
		"h": "145",
		"x": "823",
		"y": "1871",
		"txt": "名家居世博园",
		"aLink": "http://www.ffepcn.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "mingjiajushiboyuan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/yulandajuyuan.png",
		"w": "109",
		"h": "68",
		"x": "1645",
		"y": "903",
		"txt": "玉兰大剧院",
		"aLink": "http://www.dgyldjy.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yulandajuyuan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/zhonghetang.png",
		"w": "63",
		"h": "123",
		"x": "1693",
		"y": "761",
		"txt": "中和堂博物馆",
		"aLink": "http://www.zk71.com",
		"sprite": false,
		"step": 0,
		"scenepPoit": "zhonghetangbowuguan",
		"info": "国内第一个以糕点为主题的食品类博物馆，通过实物、图片、现场演示等方式，再现了我国历史悠久的传统糕点文化。</br>圣心食品有限公司于2006年开始筹建国内首个糕点博物馆及厂房和文化旅游设施，博物馆展区面积有3000多平方米，搜集了糕点类制作器具、机械、包装、仿真品、实物、与糕点相关的民俗物件及图片1000多件，展出的有300多件。展示物品从“传统的中国文化演变、岭南糕饼文化、民俗文化以及与糕点相关的历史记载”等四个方面形象生动展示了中国糕点文化。</br>博物馆注重游客的互动性，允许游客现场参与食品制作，并提供有关食品制作培训，将食品、民俗、文化有机结合在一起，让游客在食品的制作过程中，更好地了解东莞的饮食文化。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/yinpingshan.png",
		"w": "417",
		"h": "295",
		"x": "4467",
		"y": "1450",
		"txt": "东莞市清溪银瓶山森林公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "qingxiyinpingshan",
		"info": "银瓶山森林公园总体规划面积123.5平方公里，是东莞市面积最大的森林公园，主峰银瓶嘴海拔898米，为“东莞第一峰”。这里层峦叠嶂，碧水萦绕，溪谷幽深，竹木苍翠，鸟语花香，山上终年云雾缭绕、云雨变幻万千，素有“小九寨沟”之美誉。银瓶山森林公园划分为谢岗、清溪和樟木头三大片区。</br>清溪片区既有雄奇瑰丽、变幻多姿的东莞第一瀑；又有藤垂悬崖、深荫翳日的杨桥景区；还有怪石嶙峋、姿态万千的紫烟阁以及爆石奇观等景点。谢岗片区有挑战极限的“步云梯”登峰险道；又有处处碧水常流、奇石林立的“五道将军”亲水步道；还有历经沧桑、神秘莫测的观音坐莲千年古道。 </br>公园属南亚热带季风气候，年降雨量1500-2400mm，雨量集中在4-9月，年平均气温22.1℃。公园内动植物资源丰富，是名副其实的“植物王国，雀鸟天堂”。除有穗花杉、三尖杉、华南五针松、短萼仪花、禾雀花等特色各异的植物群落以外还有穿山甲、琴蛇、猫头鹰、野猪等各种野生保护动物。到目前为止，共发现植物1500多种、鸟类105种。银瓶山千峰竞秀、万木长春，是一个集旅游、休闲、科教于一体的旅游胜地，置身其中可让您远离都市的喧嚣，尽情感受大自然的乐章。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/pic/dongguandongzhan.png",
		"w": "374",
		"h": "104",
		"x": "3606",
		"y": "1311",
		"txt": "东莞东站",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "dongzhan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/qifengshan.png",
		"w": "160",
		"h": "138",
		"x": "1753",
		"y": "908",
		"txt": "旗峰公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "qifeng",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/henglizhen.png",
		"w": "262",
		"h": "269",
		"x": "3136",
		"y": "634",
		"txt": "牛文化博物馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "niuwenhua",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/yishe.png",
		"w": "395",
		"h": "111",
		"x": "2813",
		"y": "810",
		"txt": "东莞市逸颐艺舍博物馆",
		"aLink": "http://www.artsdechine.net/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yiguyishe",
		"info": "逸颐艺舍博物馆位于中国广东省东莞市横沥镇彩霞路129号，环境幽雅，设计独特。于2011年开始筹建，建筑总面积约10000平方米，馆内主体建筑有展览四合院、贵宾艺舍、藏品仓库大楼。四合院内设有主题展厅，集中展示了创办我馆的陈氏家族从上世纪七十年代开始所收藏的各类精美藏品，藏品涵盖古今书画、瓷器(唐、宋、元、明、清、民国)、青铜器(商、周、春秋、战国、秦汉)、明清家具、犀角雕、象牙雕、田黄石等，深的藏界好评。2016年被评为国家级4a景区。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/lingnanmeishuguan.png",
		"w": "216",
		"h": "70",
		"x": "1365",
		"y": "717",
		"txt": "岭南美术馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "lingnanmeishuguan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/haogang.png",
		"w": "261",
		"h": "119",
		"x": "1242",
		"y": "927",
		"txt": "蚝岗遗址博物馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "haogangyizhi",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/huizhanjiudian.png",
		"w": "178",
		"h": "148",
		"x": "1421",
		"y": "964",
		"txt": "东莞会展国际大酒店",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "houjieguoji",
		"info": "东莞观澜湖度假酒店被大屏障国家森林公园和观澜湖高尔夫球会环抱其中，由21层的酒店楼层组成。山环水抱，绿意如海，以生态、环保的绿色人文理念，建成亚洲地区顶级的山林高尔夫休闲度假酒店。酒店拥有334间不同种类型的客房及套房，是国内外宾客慕名前来的热带高尔夫度假圣地。酒店景观宽阔，湖光山色收于一室，拥有完善的配套设施，包括一个标准户外泳池、趣味十足的水上乐园，和一个室内恒温游泳池，同时还有全亚洲最大的水疗中心、高尔夫专卖店、和配有一个两千平方米的大宴会厅和38间多功能厅的国际商务会议和展览中心。度假酒店内还设有许多适合一家大小齐齐享乐的活动设施。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/nanshe.png",
		"w": "219",
		"h": "158",
		"x": "2768",
		"y": "406",
		"txt": "南社",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "nanshecun",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/dongwuyuan.png",
		"w": "258",
		"h": "132",
		"x": "2074",
		"y": "1159",
		"txt": "东莞市香市动物园",
		"aLink": "http://www.xszoo.com",
		"sprite": true,
		"step": 4,
		"scenepPoit": "xiangshidonghuyuan",
		"info": "香市动物园是东莞首个大型动物园，位于香市现代农业生态园内，占地面积700亩约合47万平方米。园内饲养了70余种1100多只来自世界各地的珍禽异兽，在动物舍建设上，突破了笼养式的传统模式，采用了大圈散养和混养的方式，并用水面、岛屿、玻璃和木栅栏进行区分各种动物的领域。拥有表演阵容强大的动物综合表演馆和海兽表演馆。除了可以观赏到白虎、狮子、河马、长颈鹿、麋鹿、黑猩猩等珍稀动物，还可以看到精彩的大象表演和海兽表演，让游客亲身体现与兽同行的刺激和快感，感受动物园带来的独有的香市韵味。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/tangwei.png",
		"w": "396",
		"h": "184",
		"x": "2341",
		"y": "484",
		"txt": "南社村和塘尾村古建筑群景区",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 4,
		"scenepPoit": "nanshecun",
		"info": "南社·塘尾明清古建筑群”位于东莞市茶山镇南社村和石排镇塘尾村内，是一处以明清时期岭南古建筑为主体、突显特色古建历史文化及传统民俗文化为内涵的综合性古村落。“南社·塘尾”古村始建于南宋，迄今已有八百多载，现存的多为明清时期的岭南古建文物，经多年的保护和修缮。</br>    如今南社古村现存祠堂家庙32座、民居250多间、古井40多口，还保存了关帝庙、土地庙、苏王庙及文庙、洪圣宫等庙宇遗址。南社古村是东莞市现存最大的古建筑群，也是广东省现存最大的古建筑群之一；而塘尾古村现存古民居268栋、祠堂21间、书房19间、古井15口、4个围门、17座炮楼。</br>    塘尾古村不仅具有鲜明的岭南古建筑特色文化，还融合了岭南地区村落的防御意识、宗族观念、儒家思想和风水理论为一体。</br>    此外，“南社·塘尾”古村还保留了大量的木雕、砖雕、石雕、灰塑及陶塑等建筑构件艺术品和丰富的壁画彩绘。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	}, {
		"url": "images/pic/dangao.png",
		"w": "266",
		"h": "180",
		"x": "2503",
		"y": "659",
		"txt": "中国圣心糕点博物馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "shengxingaodian",
		"info": "国内第一个以糕点为主题的食品类博物馆，通过实物、图片、现场演示等方式，再现了我国历史悠久的传统糕点文化。</br> 圣心食品有限公司于2006年开始筹建国内首个糕点博物馆及厂房和文化旅游设施，博物馆展区面积有3000多平方米，搜集了糕点类制作器具、机械、包装、仿真品、实物、与糕点相关的民俗物件及图片1000多件，展出的有300多件。展示物品从“传统的中国文化演变、岭南糕饼文化、民俗文化以及与糕点相关的历史记载”等四个方面形象生动展示了中国糕点文化。</br> 博物馆注重游客的互动性，允许游客现场参与食品制作，并提供有关食品制作培训，将食品、民俗、文化有机结合在一起，让游客在食品的制作过程中，更好地了解东莞的饮食文化。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/yuanchonghuan.png",
		"w": "199",
		"h": "226",
		"x": "2074",
		"y": "219",
		"txt": "袁崇焕纪念园",
		"aLink": "http://www.ych.org.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yuanchonghuan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/jiangguang.png",
		"w": "368",
		"h": "200",
		"x": "1214",
		"y": "2567",
		"txt": "蒋光鼐故居",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "jiangguangding",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/tiyuzhongxin.png",
		"w": "204",
		"h": "110",
		"x": "1410",
		"y": "824",
		"txt": "东莞滨江体育公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "binjiangtiyu",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/shilongzhen.png",
		"w": "302",
		"h": "196",
		"x": "2405",
		"y": "300",
		"txt": "仙溪福地欧公文化景区",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "xianxifudi",
		"info": "仙溪福地欧公文化景区位于东莞市石龙镇新城区西北面，是一个集寺庙观堂、文物古迹、园林景观于一体的旅游休闲文化景区。景区由石龙镇人民政府与社会资本共同投资建设，属公益性旅游文化景区，占地面积20000平方米，由欧公祠、欧仙寺、仙溪福地牌坊、接龙桥和八角亭等景点组成。其中，欧公祠为东莞市文物保护单位，接龙桥和仙溪福地牌坊则属于东莞市第一批不可移动文物。景区整体布局形成于清代中期，现仙溪福地牌坊和接龙桥基础部分均为这一时期所建原物；欧公祠于清末民初重建，在岭南传统建筑的基础上融合了西方建筑风格，现仍保存完好，是东莞地区中外文化交流的历史见证，是东莞市现存最具代表性的民国初期建筑之一。景区整体建筑历史信息和文化内涵丰富，具有重要历史价值。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/tangxia.png",
		"w": "544",
		"h": "277",
		"x": "3307",
		"y": "2434",
		"txt": "东莞观澜湖酒店",
		"aLink": "http://www.mission-hills-hotel.com/",
		"sprite": true,
		"step": 4,
		"scenepPoit": "guanlanhujiudian",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/dapingzhangsenlingongyuan.png",
		"w": "482",
		"h": "248	",
		"x": "3122",
		"y": "2215",
		"txt": "大屏嶂森林公园",
		"aLink": "http://www.dpzpark.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "dapingzhang",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/wangqiuzhongxin.png",
		"w": "272",
		"h": "128",
		"x": "1878",
		"y": "988",
		"txt": "东莞网球中心",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "wangqiuzhongxin",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/yuecai.png",
		"w": "210",
		"h": "233",
		"x": "2210",
		"y": "850",
		"txt": "悦莱花园酒店",
		"aLink": "http://www.yuelaigardendongguan.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yuelaihuayuan",
		"info": "悦莱花园酒店坐落于东莞市寮步镇新城中心区，是寮步镇行政和商业的中心地带，毗邻东莞市区，与松山湖高新科技产业园相依伴，是穗港经济走廊的中枢，区位优势得天独厚,交通十分便利。酒店拥有豪华客房、商务客房、行政客房和总统套房等各具特色；设有中、西式餐厅、商务中心、票务中心、茶艺馆、精品店、康体中心、游泳池、网球场、篮球场、大型园林式停车场等配套设施，酒店花园各种名贵的花草树木遍布其中;设有能同时容纳1000人的多功能宴会厅，可接待大型国际会议，举办大型宴会和酒会。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/chengbao.png",
		"w": "452",
		"h": "359",
		"x": "4089",
		"y": "2846",
		"txt": "龙凤山庄影视旅游区",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "longfengshanzhuang",
		"info": "龙凤山庄影视渡假村位于东莞市凤岗镇，占地38万平方米，它毗邻深圳平湖、龙岗，集餐饮、娱乐、婚纱摄影、旅游、度假休闲为一体的“轻松驿站”。渡假村内设有各式各样的游玩设施，万倾花海、“绿色长廊”、草莓基地、万棵荔枝园、千棵龙眼等生态园；“欢乐艺演台”动物表演、清明上河街民间杂技表演、梦幻西西里水上舞台大型歌舞表演、节假日大型中式、西式婚礼巡游表演，将带给游客不同的视觉体验，还有可容纳500人的大型自助烧烤场，渡假村内蓝天、白云、青山、绿水、花海、人文景观和谐共生。在2011年荣获“东莞五大特色景区之一”、“中国最佳拍摄基地”等称号,2012年2月正式被评定为国家AAAA级旅游景区，也是华南最大的婚纱外景拍摄基地。 渡假村内拥有地标式鸟笼、龙凤大殿、教堂、清明上河街等100多处特色景观，更能全方位的满足珠三角乃至全国婚纱影楼的摄影需求。 龙凤山庄配套准五星级婚嫁酒店嘉辉会酒店，500多间各具特色客房，千人宴会厅，多功能际商务会议厅，森巴游泳池、恒温池、盛世皇宫，让您商务休闲两不误，乐逍遥水疗中心，带您走进梦幻天堂，体验最高级的休闲、养生文化。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/haomendafandian.png",
		"w": "180",
		"h": "268",
		"x": "1281",
		"y": "2347",
		"txt": "豪门大饭店",
		"aLink": "http://www.grand-noble-hotel.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "haomendafandian",
		"info": "豪门大饭店是东莞首家台商独资兴建，以精致服务为宗旨的五星级商务涉外旅游饭店，处于珠江三角洲经济开发区的腹地，地理位置优越，位于五大机场中心：香港机场、深圳机场、广州机场、珠海机场、澳门机场，另广深公路、虎门高速、常虎高速、京珠高速、白沙高铁站近在咫尺，交通十分便利。饭店外墙选材为西班牙进口沙安娜大理石，采用十八世纪欧州巴洛克式建筑风格，现代化建筑的高科技与古典欧式宫廷建筑风格的完美结合，营造出古典、尊贵、豪华、艺术和追求无限完美的特质，被誉为广东最有特色的建筑之一。饭店拥有豪华客房248间，以及风格迥异的餐厅、酒吧、设备先进的豪华宴会厅、会议厅及康体娱乐休闲项目。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/gif/dongguandiyixi.png",
		"w": "474",
		"h": "243",
		"x": "4112",
		"y": "1631",
		"txt": "黄茅田瀑布",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 3,
		"scenepPoit": "huangmaotianpubu",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/richanwenti.png",
		"w": "324",
		"h": "113",
		"x": "2259",
		"y": "1063",
		"txt": "东风日产文体中心",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "dongfengrichan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/pic/huaerdeng.png",
		"w": "369",
		"h": "261",
		"x": "3666",
		"y": "900",
		"txt": "华尔登国际酒店",
		"aLink": "http://www.welltonhotel.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "huaerdeng",
		"info": "东莞华尔登国际酒店位于东莞市东部重镇--桥头镇中心文化广场侧，为挂牌五星级酒店。酒店毗邻占地五万多平方米的城市中心公园，湖光山色，一览无遗，融自然幽静与豪华时尚于一体，占地18000平方米，总建筑面积60000平方米，主楼25层，拥有豪华客房400余间/套，设中/西/日餐厅及大型宴会厅、多功能会议厅，69间设计新颖的KTV包房引领东莞娱乐新潮流，游泳池、网球场、健身房等康体设施一应俱全。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/gif/tangxiashanzhengbanshan.png",
		"w": "575",
		"h": "227",
		"x": "3716",
		"y": "2234",
		"txt": "塘厦三正半山酒店",
		"aLink": "http://www.goodviewhoteltangxia.com/",
		"sprite": true,
		"step": 4,
		"scenepPoit": "tangxiasanzhengbanshan",
		"info": "塘厦三正半山酒店位于东莞市塘厦镇行政文化中心区，是一家集商务会议、休闲度假、亲子娱乐、康体养生、温泉于一体的五星级酒店。酒店占地面积21万平方米，绿化覆盖率达到80%以上，拥有万亩城市生态保护林和40万平方米的天然水库，客房558间/套。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/yinenmen.png",
		"w": "209",
		"h": "119",
		"x": "1650",
		"y": "584",
		"txt": "迎恩门城楼",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yinenmen",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/chenxiangbowuguan.png",
		"w": "332",
		"h": "175",
		"x": "2322",
		"y": "1166",
		"txt": "中国沉香文化博物馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "chenxiangwenhua",
		"info": "中国首座最具规模的沉香文化博物馆，中国(寮步)沉香文化博物馆于2014年12月18日正式开馆。据悉，该馆位于寮步镇香市公园内，运用先进技术，重现香市历史，介绍沉香(莞香)的种植、香具的使用及展示沉香实物、各类香用品等，致力打造中国沉香文化传播的重要基地。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/dongjiangzongdui.png",
		"w": "395",
		"h": "236",
		"x": "1846",
		"y": "1776",
		"txt": "东莞市广东东江纵队旧址景区",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "dongjiangzongdui",
		"info": "依托全国重点文物保护单位大岭山抗日根据地旧址而建，现为全国青少年教育基地。展馆紧邻大王岭村抗日旧址，馆区占地 53319平方米，展览面积近2000平方米，主体建筑具有抗战时期岭南客家村落建筑风格，主题陈列内容紧扣世界反法西斯战争和中国抗日战争、解放战争的历史背景，采用幻影成像、电子沙盘、模拟场景等现代化声光电陈列布展技术，融合地域特征的艺术效果，系统地展示了东江纵队为了民族的解放事业浴血奋战的光辉历程。馆内还设有临时展厅、报告厅等，楼顶设观景台，可远眺大王岭村抗日旧址、百花洞战场和大岭山镇新貌。纪念馆以丰富翔实的东纵历史照片、文物和史料，全面展示了东江纵队为了民族的解放事业浴血奋战的光辉历程。陈列共分为九个部分，展出东纵革命文物140多件，图片450多幅，雕塑、油、版等艺术作品二十余件。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/tianbao.png",
		"w": "198",
		"h": "72",
		"x": "1637",
		"y": "695",
		"txt": "岭南美术馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "lingnanmeishuguan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/humendaqiao.png",
		"w": "647",
		"h": "232",
		"x": "570",
		"y": "2500",
		"txt": "虎门大桥",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "humendaqiao",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/pic/bahaolou.png",
		"w": "327",
		"h": "238",
		"x": "3182",
		"y": "1298",
		"txt": "汇华国际饭店",
		"aLink": "http://www.huihuahotel.com.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "huihuaguoji",
		"info": "汇华国际饭店，是建汇集团旗下一家名牌五星级的大型酒店.它坐落于港澳两地“大京九”沿线第一站——常平镇的繁华商业区中心地带的常平大道，交通十分便利。汇华国际饭店拥有各类客房600多间，中西餐厅、卡拉OK房、另设有商务中心、日式酒吧、健身等康乐设施及服务设施，功能非常齐全.汇华国际饭店雅致的环境、高档的设施、优质的服务、专业的管理将让客人倍感尊贵。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/pic/mayongzhen.png",
		"w": "548",
		"h": "389",
		"x": "308",
		"y": "592",
		"txt": "华阳湖湿地公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "huayanghu",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/lunchuan.png",
		"w": "280",
		"h": "128",
		"x": "543",
		"y": "2763",
		"txt": "轮船",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 3,
		"scenepPoit": "",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/shatian.png",
		"w": "413",
		"h": "206",
		"x": "539",
		"y": "1330",
		"txt": "粤晖园旅游景区",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "aohuiyuan",
		"info": "“北游颐和园，南游粤晖园”。粤晖园是岭南园林的杰作，是一座占地面积50余公顷、总投资3亿元人民币的大型私家园林。粤晖园地处东江支流下游水网密布的道滘镇，毗邻珠江口,占地面积50余公顷，总投资3亿元人民币，是中国最大的古典园林之一。粤晖园布局精妙, 将岭南园林传统艺术与现代审美情趣融合于一园，楼馆、亭台、水榭、曲廊、石桥、假山等108个园林景点，蕴含着清雅别致的岭南古建筑风格，掩映于青翠欲滴的古树名木之间，曲径通幽,步移景异。蘩文馆是园中的主体建筑，面积一万多平方米，为岭南仿古楼阁之冠，珍藏着岭南文化艺术瑰宝。南韵馆则是古典剧场，可聆听传统粤曲的天籁之音。五元坊、诗廊、归水桥等众多景点，工艺精湛，富于岭南文化气息。粤晖园展现了恢弘壮阔的历史画卷和旖旎多姿的水乡风情，集观光度假、休闲娱乐、艺术鉴赏、拓展培训为一体的旅游胜地。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/shangtun.png",
		"w": "306",
		"h": "143",
		"x": "1850",
		"y": "1052",
		"txt": "东莞唐拉雅秀酒店",
		"aLink": "http://www.sheraton.com",
		"sprite": false,
		"step": 0,
		"scenepPoit": "tanglayaxiu",
		"info": "唐拉雅秀酒店位于东莞东城区，山环水绕，邻近虎英公园和湖泊，交通便利，地理位置优越。酒店拥有268间豪华客房和湖景套房以及跃层套房，设有总面积逾2208平方米的先进会议中心，拥有一个大宴会厅和11间会议厅，5个汇集中西日美食的餐厅和2个酒吧。此外，还有典雅温馨的SPA和健身中心、美容美发等多种娱乐设施。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/pic/changanzhenhonglou.png",
		"w": "437",
		"h": "203",
		"x": "1553",
		"y": "2374",
		"txt": "丰泰花园酒店",
		"aLink": "http://www.richwoodgardenhotel.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "fengtaihuayuan",
		"info": " 丰泰花园酒店荣膺国家五星级旅游饭店、鲁班奖工程、五钻特级酒家等殊荣。酒店素有东方建筑文化艺术酒店美誉，具有浓厚的热带雨林风情。430间豪华商务客房，8个风格各异的餐厅和酒吧，有可容纳1300多人的国际会议中心及9间多功能豪华商务会议室。休闲设施包括KTV、沐足、健康会馆、大型室外游泳池、康体中心、孔雀观赏园、亲子蔬菜园、植物园、环湖绿道、城市热矿泉等。酒店将以其舒适优雅的环境、别具特色的美食、独具匠心的休闲项目，致力于成为珠三角地区高星级酒店的典范，并竭诚为各方宾客提供尽善尽美的尊贵服务。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/houjieguojidajiudian.png",
		"w": "199",
		"h": "293",
		"x": "1101",
		"y": "1317",
		"txt": "厚街国际大酒店",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "houjieguoji",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/liaoxia.png",
		"w": "218",
		"h": "196",
		"x": "869",
		"y": "1449",
		"txt": "东莞喜来登大酒店",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "xilaideng",
		"info": "东莞喜来登大酒店置身于东莞市繁华厚街区的中心地带，地理位置便利。 迷人的都市风景和友好的工作人员能让客人获得宾至如归的温馨体验。 酒店拥有500 间精心设计的客房，家具精美、设施舒适、服务便利。无论是组织重要的商业会晤、参加会议，还是探索中国悠久的历史古迹，都会在此享受到热情周到的优质服务。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/xiping.png",
		"w": "200",
		"h": "120",
		"x": "1519",
		"y": "1098",
		"txt": "东莞市科学技术博物馆",
		"aLink": "http://www.dgstm.org.cn",
		"sprite": false,
		"step": 0,
		"scenepPoit": "kejijishubowuguan",
		"info": "主要展示制造业科技和信息高新技术两大主题，同时兼顾启蒙科技、网上科技馆、影视天地三大辅题，是国内首创的具有东莞特色和现代意义的专题科技馆。馆内展品达300多件（套），90%为互动展品，80%为创新展品，在行业内地位较高，是东莞科技旅游示范点。占地面积4万平方米，建筑面积4万平方米，展示面积1.2万平方米，总投资3亿元人民币，建筑和投资规模继上海科技馆和中国科技馆之后。拥有华南地区第一家IMAX球幕影院、4D动感影院、普通电影院兼多功能报告厅，能与欧美同步放映科技大片和故事大片。是举办学术交流、科普会议、教育培训等重要场所。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/dongcheng.png",
		"w": "157",
		"h": "92",
		"x": "1801",
		"y": "843",
		"txt": "东莞星河城",
		"aLink": "http://www.dgdynacity.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "xinghecheng",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/jiahuadajiudian.png",
		"w": "385",
		"h": "303",
		"x": "857",
		"y": "1549",
		"txt": "嘉华大酒店 ",
		"aLink": "http://www.regalhoteldongguan.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "jiahuadajiudian",
		"info": "嘉华大酒店是一家五星级航母型会展酒店，占地面积4.5万平方米，建筑面积21万平方米。 紧邻广深高速公路及高铁站； 53层酒店主体，东莞市的标志性建筑； 高科技含量的客房及套房，包括城市顶级会所--牡丹会； 2700㎡ 超大型宴会厅，配备60㎡ LED高清显示屏，可容纳3000人会议和2000人盛宴；20间豪华多功能厅、会议室和贵宾接待室；8间别具风格的餐厅及酒吧，汇集中、日、意大利及西班牙等国际美食；一应俱全的康体设施，带给您全身心的舒适体验。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/dayoulun.png",
		"w": "426",
		"h": "247",
		"x": "812",
		"y": "2723",
		"txt": "东莞港",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "dongguangang",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/gif/longzhou.png",
		"w": "470",
		"h": "142",
		"x": "579",
		"y": "838",
		"txt": "龙舟",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 3,
		"scenepPoit": "",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/changpingzhen.png",
		"w": "317",
		"h": "183",
		"x": "2946",
		"y": "1239",
		"txt": "隐贤山庄",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yinxianshanzhuang",
		"info": "东莞丽城隐贤山庄旅游风景区位于东莞市常平镇。地处东莞交通枢纽中心地域，东莞东火车站、常平火车站、常平汽车站到达隐贤山庄仅需5分钟车程地理位置优越。1998年全面对外开放，原国家主席杨尚昆先生为隐贤山庄做了亲笔题名。占地面积1800亩，山灵水秀，风景怡人，因明末贤臣李觉斯于此隐居而得名。隐贤山庄景区布局优美雅致，浑然而成。星罗棋布的人文景观;大肚弥勒佛，大清宫，月华泉，独脚天蟾，佛香塔，仙人床等集中反映了我国儒、佛、道各家傅统文化的寓意内涵。每年一度的荔枝节吸引了国内外上百万的游客。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/diaolou.png",
		"w": "206",
		"h": "245",
		"x": "4417",
		"y": "2606",
		"txt": "碉楼",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "fenggangkejiadiaolou",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/tianeta.png",
		"w": "392",
		"h": "400",
		"x": "4479",
		"y": "1722",
		"txt": "大王山森林公园",
		"aLink": "http://www.dgmkfp.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "dawangshan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/wushi.png",
		"w": "263",
		"h": "391",
		"x": "4336",
		"y": "1801",
		"txt": "舞麒麟",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 2,
		"scenepPoit": "",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/jindiaoxiang.png",
		"w": "136",
		"h": "177",
		"x": "1220",
		"y": "2817",
		"txt": "滨海新湾区",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "binhaixinwanqu",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/zhongtang.png",
		"w": "248",
		"h": "105",
		"x": "787",
		"y": "477",
		"txt": "养蜂源蜜蜂王国",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yangfengyuan",
		"info": "东莞市养生源蜂业有限公司成立于1995年（创始人何胜先生拥有40多年的养蜂历史），是一家集专业养蜂、蜂产品科研开发、连锁式蜂产品专卖于一体的现代化民营企业。作为中国养蜂学会、中国蜂产品协会会员单位，公司拥有现代化的物流体系，其蜂产品专卖店遍布全国各地，是致力于锻造蜂业中之精品的“名牌产品”、“金奖产品”企业和科普教育基地",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/gaoerfu.png",
		"w": "150",
		"h": "309",
		"x": "3693",
		"y": "2516",
		"txt": "观澜湖高尔夫球会",
		"aLink": "http://www.missionhillsgroup.com",
		"sprite": true,
		"step": 4,
		"scenepPoit": "gaoerfuqiuhui",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/shatianzhen.png",
		"w": "279",
		"h": "162",
		"x": "606",
		"y": "1583",
		"txt": "穗丰年湿地公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "suifengnian",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/wangniuyihao.png",
		"w": "150",
		"h": "133",
		"x": "960",
		"y": "584",
		"txt": "旺牛一号",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "wangniuyihao",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},

	{
		"url": "images/pic/nancheng.png",
		"w": "197",
		"h": "158",
		"x": "1697",
		"y": "1028",
		"txt": "东莞汇一城",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "huiyicheng",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/tongshashengtaigongyuan.png",
		"w": "447",
		"h": "448",
		"x": "1797",
		"y": "1204",
		"txt": "东莞市同沙生态公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 4,
		"scenepPoit": "tongshashengtaigongyuan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/fuyingyagaomeijuejiudian.png",
		"w": "236",
		"h": "215",
		"x": "1125",
		"y": "1172",
		"txt": "富盈雅高美爵酒店",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "fuyinyagaomeijue",
		"info": "富盈酒店位于广深高速公路东莞出口与东莞大道交汇处，是东莞最临近广州、深圳的五星级酒店之一，优越的地理位置、便利的交通环境，为经常往返于粤港澳的客人提供了便捷而高效的居停之所。260间温馨舒适的客房精致而典雅；中餐厅、西餐厅、法日餐厅、大堂吧为宾客提供琳琅满目的中西特色美食；宴会中心11个不同规格的多功能厅，是举办婚庆喜宴、公司庆典、商务研讨、专业培训的最佳场所，从10人到2000人的会议接待规格，满足您全方位的需要。秉承“舒适、体贴”的富盈待客之道，富盈酒店开业以来，获得五星级酒店、五钻级酒家、广东省著名商标等诸多殊荣，得到了广大宾客的青睐。酒店时尚独特的建筑风格、先进齐全的配套设施，品质非凡的餐厅出品，以及专业有素、细致入微的服务团队，从各个角度共同营造为您营造一个理想的家外之家。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/gongyuanxiaoting.png",
		"w": "329",
		"h": "181",
		"x": "2384",
		"y": "906",
		"txt": "佛灵湖郊野公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 4,
		"scenepPoit": "folinghu",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/qiaotouzhen.png",
		"w": "273",
		"h": "140",
		"x": "3828",
		"y": "779",
		"txt": "莲湖公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 4,
		"scenepPoit": "lianhuashanzhuang",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/guancheng.png",
		"w": "248",
		"h": "107",
		"x": "1805",
		"y": "736",
		"txt": "东莞万达广场",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "wandaguangchang",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/keyuan.png",
		"w": "216",
		"h": "210",
		"x": "1503",
		"y": "661",
		"txt": "可园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "keyuan",
		"info": "可园博物馆位于广东省东莞市莞城区博厦村西部，为清代广东四大名园之一。2001年被国务院公布为全国重点文物保护单位。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	}, {
		"url": "images/gif/songshanhu.png",
		"w": "500",
		"h": "487",
		"x": "2130",
		"y": "1509",
		"txt": "松山湖景区",
		"aLink": "http://www.ssl.gov.cn",
		"sprite": true,
		"step": 4,
		"scenepPoit": "songshanhu",
		"info": "规划控制面积72平方公里，坐拥8平方公里的淡水湖和14平方公里的生态绿地，保持着完好的充满岭南气息的原生态绿地，绿化覆盖率超过了60%。8平方公里水面的松山湖，四周峰峦环抱，湖面烟波浩渺。开发出了“生态游”、“工业游”和“科技游”三大旅游产品，有松湖烟雨、松湖花海、状元笔公园、月荷湖公园、梦幻百花谷、桃源公园等主要景点，是集游览、休闲、度假、健身娱乐于一体的国家AAAA级旅游景区。创意生活城是松山湖整体生活配套的中心，也是“东莞制造”产业支持中心的载体，建立了东莞“名牌产品直销中心”，展销东莞知名产品，包括徐福记、圣心、华美等。松山湖先后被评为“中国最具发展潜力的高新技术产业开发区”、“国家电子信息产业基地”、“部省市共建国家火炬创新创业园试点计划”、“跨国公司最佳投资的开发区”、“中国青年留学人员创业基地”、“国家高新技术创业服务中心”。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/bolilou.png",
		"w": "251",
		"h": "131",
		"x": "1421",
		"y": "503",
		"txt": "东莞市民艺术中心",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "yishuzhongxin",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/ouya.png",
		"w": "384",
		"h": "228",
		"x": "3387",
		"y": "1024",
		"txt": "欧亚国际酒店",
		"aLink": "http://www.chengxiang-dongguan.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "ouyaguoji",
		"info": "欧亚国际酒店集餐饮、商务和娱乐于一体的豪华商务酒店，拥有 423间设计独特的客房及套房，设有中、西餐厅及日式餐厅、大堂吧、国际宴会厅和多个独立会议室、健身房等健身设施，2012年5月3日，正式挂牌为国家五星级饭店。",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/hongchuan.png",
		"w": "297",
		"h": "166",
		"x": "714",
		"y": "2900",
		"txt": "红船",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 3,
		"scenepPoit": "",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/meisiweierdun.png",
		"w": "192",
		"h": "233",
		"x": "1099",
		"y": "2354",
		"txt": "东莞虎门美思威尔顿酒店",
		"aLink": "http://www.humen-sofitel.com/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "meisiweierdun",
		"info": "美思威尔顿酒店及度假村管理集团的品牌定位于以物超所值的价格为客人提供温暖舒适的个性化及贴身管家服务，旨在满足每一位客人对国际奢华酒店体验的需求，致力于为宾客打造 “回家”的入住体验。为精明的游客留下难忘的美好回忆。酒店致力传承“真诚、亲切和个性化”的服务理念，并满足每一位顾客对国际奢华酒店的需求，让客人感受“家外之家”的完美住宿体验！ ",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/changanting.png",
		"w": "290",
		"h": "163",
		"x": "1615",
		"y": "2628",
		"txt": "孙中山先祖故居",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "sunzhongshan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/changanzhenbieshu.png",
		"w": "339",
		"h": "180",
		"x": "1795",
		"y": "2248",
		"txt": "莲花山庄",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 4,
		"scenepPoit": "lianhuashanzhuang",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/gif/pubugongyuan.png",
		"w": "558",
		"h": "280",
		"x": "1332",
		"y": "1537",
		"txt": "水濂山森林公园",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": true,
		"step": 4,
		"scenepPoit": "shuilianshan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/wanjiang.png",
		"w": "212",
		"h": "139",
		"x": "1272",
		"y": "727",
		"txt": "华南MALL-欢笑天地",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/dalingshan.png",
		"w": "387",
		"h": "209",
		"x": "1657",
		"y": "1828",
		"txt": "大岭山森林公园",
		"aLink": "http://lyj.dg.gov.cn/dlsgydt/1505.jhtml",
		"sprite": false,
		"step": 0,
		"scenepPoit": "dalingshan",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/haizhanbowuguan.png",
		"w": "288",
		"h": "132",
		"x": "925",
		"y": "2564",
		"txt": "海战博物馆",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "haizhanbowuguan",
		"info": '海战博物馆，鸦片战争博物馆(虎门林则徐纪念馆、海战博物馆，三个馆名一套班子)，坐落于广东省东莞市虎门，是纪念性和遗址性相结合的专题博物馆，管理的林则徐销烟池与虎门炮台旧址是全国重点文物保护单位，是鸦片战争时期的历史见证，管理面积约80万平方米。鸦片战争博物馆始建于1957年，建馆初期馆名为"林则徐纪念馆"，1972年更名为"鸦片战争虎门人民抗英纪念馆"，1985年重新定名为"虎门林则徐纪念馆"，为利于对鸦片战争遗址的管理，又增加一个馆名--鸦片战争博物馆。',
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	}, {
		"url": "images/pic/dalingshanzhen.png",
		"w": "423",
		"h": "181",
		"x": "2130",
		"y": "1580",
		"txt": "大岭山镇",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/zhongxinguangchang.png",
		"w": "109",
		"h": "103",
		"x": "1585",
		"y": "813",
		"txt": "中心广场",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "zhongxinguangchang",
		"info": "",
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	},
	{
		"url": "images/pic/weiyuanpaotai.png",
		"w": "197",
		"h": "121",
		"x": "828",
		"y": "2593",
		"txt": "威远炮台",
		"aLink": "http://dgtour.dg.gov.cn/",
		"sprite": false,
		"step": 0,
		"scenepPoit": "weiyuanpaotai",
		"info": '威远炮台位于中国珠江出口的穿鼻洋北武山脚下，南山炮台前滩岩石正中。和镇远、靖远两炮台形成一"品"字，并与横档、永安、巩固等炮台构成鸦片战争时期虎门海防的第二重门户。炮台间系有铁链木桩于水中，阻碍敌船行驶;炮台火力交织，控制洋面，在狭长的江面上形成坚固的阵地。威远炮台总共安炮40门，曾是潮州总兵李廷钰和守军于1841年1、2月份浴血奋战的地方，遗迹尚存。',
		"infoImage": ["1.jpg", "2.jpg", "3.jpg"]
	}
];