
var imagesFile = [
	"images/img_07.png",
	"images/img_08.png",
	"images/img_09.png",
	"images/img_10.png",
	"images/img_11.jpg",
	"images/img_15.png",
	"images/img_18.png",
	"images/img_19.png",
	"images/img_14.png",
	"images/img_2000.png",
	"images/img_1600.png",
	"images/img_cebian.png",
	"images/img_159.png",
	"images/img_xingneng.png",
	"images/vivo_119.jpg",
	"images/frame/vivo_118.jpg",
	"images/img_62.png",
	"images/img_63.png"
];

var frame_file_1 = [
	"images/frame/vivo_1.png",
	"images/frame/vivo_2.png",
	"images/frame/vivo_3.png",
	"images/frame/vivo_4.png",
	"images/frame/vivo_5.png",
	"images/frame/vivo_6.png",
	"images/frame/vivo_7.png",
	"images/frame/vivo_8.png",
	"images/frame/vivo_9.png",
	"images/frame/vivo_10.png"	
];
var frame_file_2 = [
	"images/frame/vivo_11.png",
	"images/frame/vivo_12.png",
	"images/frame/vivo_13.png",
	"images/frame/vivo_14.png",
	"images/frame/vivo_15.png",
	"images/frame/vivo_16.png",
	"images/frame/vivo_17.png",
	"images/frame/vivo_18.png",
	"images/frame/vivo_19.png",
	"images/frame/vivo_20.png",
	"images/frame/vivo_21.png",
	"images/frame/vivo_22.png",
	"images/frame/vivo_23.png",
	"images/frame/vivo_24.png",
	"images/frame/vivo_25.png",
	"images/frame/vivo_26.png",
	"images/frame/vivo_27.png",
	"images/frame/vivo_28.png",
	"images/frame/vivo_29.png",
	"images/frame/vivo_30.png",
	"images/frame/vivo_31.png",
	"images/frame/vivo_32.png",
	"images/frame/vivo_33.png",
	"images/frame/vivo_34.png",
	"images/frame/vivo_35.png",
	"images/frame/vivo_36.jpg",
	"images/frame/vivo_37.jpg",
	"images/frame/vivo_38.jpg",
	"images/frame/vivo_39.jpg",
	"images/frame/vivo_40.jpg",
	"images/frame/vivo_41.jpg",
	"images/frame/vivo_42.jpg",
	"images/frame/vivo_43.jpg",
	"images/frame/vivo_44.jpg",
	"images/frame/vivo_45.jpg",
	"images/frame/vivo_46.jpg",
	"images/frame/vivo_47.jpg",
	"images/frame/vivo_48.jpg",
	"images/frame/vivo_49.jpg",
	"images/frame/vivo_50.jpg",
	"images/frame/vivo_51.jpg",
	"images/frame/vivo_52.jpg",
	"images/frame/vivo_53.jpg",
	"images/frame/vivo_54.jpg",
	"images/frame/vivo_55.jpg",
	"images/frame/vivo_56.jpg",
	"images/frame/vivo_57.jpg",
	"images/frame/vivo_58.jpg",
	"images/frame/vivo_59.jpg",
	"images/frame/vivo_60.jpg",
	"images/frame/vivo_61.jpg",
	"images/frame/vivo_62.jpg",
	"images/frame/vivo_63.jpg",
	"images/frame/vivo_64.jpg",
	"images/frame/vivo_65.jpg",
	"images/frame/vivo_66.jpg",
	"images/frame/vivo_67.jpg",
	"images/frame/vivo_68.jpg",
	"images/frame/vivo_69.jpg",
	"images/frame/vivo_70.jpg",
	"images/frame/vivo_71.jpg",
	"images/frame/vivo_72.jpg",
	"images/frame/vivo_73.jpg",
	"images/frame/vivo_74.jpg",
	"images/frame/vivo_75.jpg",
	"images/frame/vivo_76.jpg",
	"images/frame/vivo_77.jpg",
	"images/frame/vivo_78.jpg",
	"images/frame/vivo_79.jpg",
	"images/frame/vivo_80.jpg",
	"images/frame/vivo_81.jpg",
	"images/frame/vivo_82.jpg"
//	"images/frame/vivo_83.jpg",
//	"images/frame/vivo_84.jpg",
//	"images/frame/vivo_85.jpg",
//	"images/frame/vivo_86.jpg",
//	"images/frame/vivo_87.jpg",
//	"images/frame/vivo_88.jpg",
//	"images/frame/vivo_89.jpg",
//	"images/frame/vivo_90.jpg",
//	"images/frame/vivo_91.jpg",
//	"images/frame/vivo_92.jpg",
//	"images/frame/vivo_93.jpg",
//	"images/frame/vivo_94.jpg",
//	"images/frame/vivo_95.jpg",
//	"images/frame/vivo_96.jpg",
//	"images/frame/vivo_97.jpg",
//	"images/frame/vivo_98.jpg",
//	"images/frame/vivo_99.jpg",
//	"images/frame/vivo_100.jpg",
//	"images/frame/vivo_101.jpg",
//	"images/frame/vivo_102.jpg",
//	"images/frame/vivo_103.jpg",
//	"images/frame/vivo_104.jpg",
//	"images/frame/vivo_105.jpg",
//	"images/frame/vivo_106.jpg",
//	"images/frame/vivo_107.jpg",
//	"images/frame/vivo_108.jpg",
//	"images/frame/vivo_109.jpg",
//	"images/frame/vivo_110.jpg",
//	"images/frame/vivo_111.jpg",
//	"images/frame/vivo_112.jpg",
//	"images/frame/vivo_113.jpg",
//	"images/frame/vivo_114.jpg",
//	"images/frame/vivo_115.jpg",
//	"images/frame/vivo_116.jpg",
//	"images/frame/vivo_117.jpg",
//	"images/frame/vivo_118.jpg"
];
